export const EMP_DATA_UPDATE = 'EMP_DATA_UPDATE';
export const EMP_DATA_LOADING = 'EMP_DATA_LOADING';
export const EMP_DATA_LOADING_COMPLETE = 'EMP_DATA_LOADING_COMPLETE';
export const EMP_DATA_LOADING_ERROR = 'EMP_DATA_LOADING_ERROR';
